-- CreateEnum
CREATE TYPE "PRODUCT_QUALITY" AS ENUM ('ORIGINAL', 'REACONDICIONADO');

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "product_quality" "PRODUCT_QUALITY" NOT NULL DEFAULT 'REACONDICIONADO';
